name: Compilation on Windows

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Boost
        run: |
          $url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.75.0/boost_1_75_0-msvc-14.2-64.exe"
          (New-Object System.Net.WebClient).DownloadFile($url, "$env:TEMP\boost.exe")
          Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\\hostedtoolcache\\windows\\Boost"
          echo "BOOST_ROOT=C:\\hostedtoolcache\windows\\Boost\\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "BOOST_LIBRARYDIR=C:\\hostedtoolcache\\windows\\Boost\\lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo ";C:\\hostedtoolcache\\windows\\Boost" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Cmake
        run: |
          mkdir build
          cd build
          cmake ..
      - name: MSVC
        run: cmake --build build --target bomberman --config release
      - name: Archive production artifact
        uses: actions/upload-artifact@v1
        with:
          name: bomberman.exe
          path: build\Bomberman\Release\bomberman.exe