name: Run unit tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2

      - name: CMake
        run: mkdir build && cd build && cmake ..
      - name: Makefile
        run: make -C build unit_tests
      - name: Run unit tests
        run: ./build/unit_tests